### ISSUE TITLE
REQUEST: Signed binaries

### ISSUE THREAD

**Issue by AndrewRathbun** [strozfriedberg/notatin#1]
Hello,

Any chance the binaries provided in the Releases could be signed? Chromium is flagging it during download and Symantec is flagging everytime I attempt to test the tool out. I signed both `reg_dump` and `reg_compare` locally with my own certificate and it solved the Symantec issue. I'm sure it would solve the Chromium issue, as well.

Thanks,

Andrew

**Comment by sf-jonstewart** [comment]
Good call. I'll try to climb this mountain again... 😂

**Comment by sf-jonstewart** [comment]
Making progress...

**Comment by kastonework** [comment]
Complete. The binaries for the existing release have been signed, and all future release binaries will be as well.
