### ISSUE TITLE
Publish notatin to crates.io

### ISSUE THREAD

**Issue by voidbar** [strozfriedberg/notatin#2]
I think it would be nice to have this in crates.io so this awesome crate could get some attention and use from more Rust developers. I think hitting 1.0 version milestone is a great time for that.

**Comment by kastonework** [comment]
Yes! This is on our very near-term roadmap; we haven't gone through the process of posting anything to crates.io yet, so it's a bit of an unknown as to the effort but it's something we intend to do really soon. I'll keep you guys updated.

**Comment by alexkornitzer** [comment]
They have made it very easy to do. IIRC you just create token and run cargo publish.

**Comment by voidbar** [comment]
Would be happy to lend a hand to help with that if needed.

**Comment by kastonework** [comment]
Thx for the offer, @voidbar!
@alexkornitzer is right, and it does look straightforward. We need to add a couple package tags to the toml, and we have a couple of updates that we want to push as well. It should be up on crates.io by the end of this week.

**Comment by sf-jonstewart** [comment]
Thanks for nudging us on this. @alexkornitzer I had no idea that chainsaw was using notatin, but that's awesome. To you both, and the public at large, we would _love_ to know about notatin integrations/use cases, whether open source or proprietary. Also, we're happy for any feedback on documentation, whether there's anything that's confusing or under-documented. My corporate email address is jonathan.stewart@aon.com.

**Comment by alexkornitzer** [comment]
Hey @sf-jonstewart, its a lesser know feature of Chainsaw but we are slowly adding additional file parsers as and when they are required (no point reinventing the wheel). Notatin seemed to fit the use case perfectly for shimcache analysis and now additionally allows Chainsaw to arbitrarily hunt and search through hives. I did not implement the feature so I can't comment on how it was to work with or about use cases, but @56616c6f72 might be able to chime in.

**Comment by kastonework** [comment]
It's alive! https://crates.io/crates/notatin
Please let us know if you run into any weirdness.
